// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1653301649);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1653301649);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1653301631);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 107);
user_pref("browser.newtabpage.activity-stream.impressionId", "{e5991415-5040-4b78-b0d6-1b92bd892c73}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1653301642");
user_pref("browser.slowStartup.averageTime", 24611);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20210318103112");
user_pref("browser.startup.homepage_override.mstone", "87.0");
user_pref("browser.startup.lastColdStartupCheck", 1653301641);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "87.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210318103112");
user_pref("extensions.lastAppVersion", "87.0");
user_pref("extensions.lastPlatformVersion", "87.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_picture_in_picture_overrides", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"bde19468-2211-4f0c-ab31-54067148801d\",\"formautofill@mozilla.org\":\"0e1a0a6f-db4d-46ca-bec3-ed14c744fc8d\",\"screenshots@mozilla.org\":\"cce2a466-e3eb-4044-9e0d-e34bba5e8093\",\"webcompat-reporter@mozilla.org\":\"39b10bf7-4ed5-41cd-9992-f898030be891\",\"webcompat@mozilla.org\":\"9ca18819-f9a7-4c33-b45d-48c0a98a45ed\",\"default-theme@mozilla.org\":\"b97950be-9bd9-417a-b630-3a74f501e7a5\",\"google@search.mozilla.org\":\"35c7cd34-0103-4f3d-8468-e2eafedb97f3\",\"amazondotcom@search.mozilla.org\":\"2501b251-e07b-44f8-a8e2-7acc1b8d72a5\",\"wikipedia@search.mozilla.org\":\"3897f220-ea20-4872-aabe-30a831cfb373\",\"bing@search.mozilla.org\":\"37f7e39e-5554-45e7-9329-e08c662b4064\",\"ddg@search.mozilla.org\":\"54d3b089-eba5-46c1-bcc4-f394f8e22d5c\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "cb66b37f-172f-4f8a-a8c1-b9aed2b85cce");
user_pref("security.sandbox.plugin.tempDirSuffix", "63eff96f-e15f-4ce2-aa7e-7edbb9f8f393");
user_pref("toolkit.startup.last_success", 1653301619);
user_pref("toolkit.telemetry.cachedClientID", "118cccea-541f-417d-915c-fefb94c3f01f");
user_pref("toolkit.telemetry.previousBuildID", "20210318103112");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
